const APP_NAME = {
	SPLASH: 'Splash',
	ONBOARDING: 'Onboarding',
	AUTH: 'Auth',
	BOTTOM_TAB: 'BottomTab',
	LOGIN: 'Login',
	REGISTER: 'Register',
	FORGOT: 'Forgot',
	HOME: 'Home',
	MESSAGE: 'Message',
	POST: 'Post',
	NOTIFICATION: 'Notification',
	PROFILE: 'Profile',
	REPORT: 'Report',
	MANAMENT: 'Manament',
	SHOP: 'Shop',
	ROLE: 'Role',
	NODE: 'Node',
	MENU: 'Menu',
	MENU_DETAIL: 'MenuDetail',
	ADD_MENU: 'AddMenu',
	DELETE_MENU: 'DeleteMenu',
	EDIT_MENU: 'EditMenu',
	SHOP_DETAIL: 'ShopDetail',
	ADD_SHOP: 'AddShop',
	DELETE_SHOP: 'DeleteShop',
	EDIT_SHOP: 'EditShop',
	USER: 'User',
	USER_DETAIL: 'UserDetail',
	ADD_USER: 'AddUser',
	EDIT_USER: 'EditUser',
	DELETE_USER: 'DeleteUser',
	MANAGE: 'Manage',
	ROLE: 'Role',
	ADD_ROLE: 'AddRole',
	EDIT_ROLE: 'EditRole',
	DELETE_ROLE: 'DeleteRole',
	DISH_DETAIL: 'DishDetail',
	DELETE_DISHES: 'DeleteDishes',
	EDIT_DISH: 'EditDish',
	CREATE_DISH: 'CreateDish'
}

module.exports = APP_NAME
